### ISSUE TITLE
Question: How to access parsed body in the mock server

### ISSUE THREAD

**Issue by steveworkman** [enjoycoding/vite-plugin-mock-server#12]
I'm looking for a way to get the body in the connect handle - is there a way to set up the `body-parser` middleware here?

**Comment by mumashanren** [comment]
I don't understand, please try to explain, it is best to provide pseudo code.

**Comment by steveworkman** [comment]
This server intercepts all requests - I'd like to inspect the body of the request - but without the `body-parser` middleware, this is difficult. Is there a way to add this in?

**Comment by maapteh** [comment]
Any plans for making this @mumashanren ?
I first thought why so few downloads until i got my POST scenario into the app :)

**Comment by maapteh** [comment]
Hi @mumashanren i made it working without a plugin, shall i send a PR?
