### ISSUE TITLE
`logLevel` has no effect

### ISSUE THREAD

**Issue by moltar** [enjoycoding/vite-plugin-mock-server#13]
I have set `logLevel: 'error',` in the config file, yet I keep seeing output like:

```
[vite-plugin-mock-server] mock server started. options = {
  mockRootDir: '....',
  urlPrefixes: [ '/api/' ],
  logLevel: 'error',
  mockJsSuffix: '.mock.js',
  mockTsSuffix: '.mock.ts',
  noHandlerResponse404: true,
  mockModules: [
    '...'
  ]
}
```

**Comment by mumashanren** [comment]
Yes, this information is printed only once at startup. The intention is to let users know what they have configured.

**Comment by moltar** [comment]
Right, but I think if I choose to have no logging, then it shouldn't print anything.
