### ISSUE TITLE
How set statusCode?

### ISSUE THREAD

**Issue by maximzhurkin** [enjoycoding/vite-plugin-mock-server#25]
please add ability to set status code for responses

**Comment by reinerBa** [comment]
There is a hint in line 137 in the index.ts
 
[res.statusCode = 404](https://github.com/enjoycoding/vite-plugin-mock-server/blob/main/src/index.ts#L137C7-L137C27)

Example
```` javascript
  {
    pattern: '/api/test1/1',
    handle: (req, res) => {
      res.statusCode = 404
      res.end('Hello world!' + req.url)
    }
  },
````
