### ISSUE TITLE
"require is not defined" error when using plugin in ESM project

### ISSUE THREAD

**Issue by johnhunter** [enjoycoding/vite-plugin-mock-server#30]
Node: v20.11.0
Vite: 5.1.1
vite-plugin-mock-server: 1.1.2
Package:
```JSON
{
  "type": "module",
}
```

Added the plugin to a vite project with the default mock module location. Starting the dev server resulted in a `require is not defined` error:

```sh
[vite-plugin-mock-server] [
  'watched root dir is',
  '[...]/mock'
]
[vite-plugin-mock-server] [
  'recursive loading mock modules',
  '[...]/mock'
]
[vite-plugin-mock-server] [
  'loading mock module',
  '[...]/mock/endpoints.mock.js'
]
[vite-plugin-mock-server] [
  'delete module cache',
  '[...]/mock/endpoints.mock.js'
]
file:///[...]/node_modules/vite-plugin-mock-server/dist/index.js:193
    delete require.cache[moduleName];
    ^

ReferenceError: require is not defined

```
It might be related to, or resolved by https://github.com/enjoycoding/vite-plugin-mock-server/pull/29 ?

Am unable to verify the example from the plugin repo as npm install gives the following error:
```
npm ERR! code CERT_HAS_EXPIRED
npm ERR! errno CERT_HAS_EXPIRED
npm ERR! request to https://registry.npm.taobao.org/to-regex-range/download/to-regex-range-5.0.1.tgz failed, reason: certificate has expired
```

**Comment by tGrefsrud** [comment]
#29 resolves it, hopefully it will be merged soon. I tried just making the changes from the PR locally and it fixed the issue for me, but that is just a temp fix and not ideal in the long run.

**Comment by octoape** [comment]
PR https://github.com/enjoycoding/vite-plugin-mock-server/pull/29 has been merged, thank you for @reinerBa contribution.
