### ISSUE TITLE
Server middleware is applied for every route

### ISSUE THREAD

**Issue by arfedulov** [enjoycoding/vite-plugin-mock-server#32]
Thanks for this plugin, it is very helpfull!

Given a configuration in vite.config.ts
```ts
plugins: [
    vue(),
    mockServer({
      urlPrefixes: [
        '/api/messages'
      ],
      middlewares: [
        (req, res, next) => {
          console.log('Apply middleware for', req.url)
          next()
        }
      ]
    })
  ],
```
I expect (and really need to) the vite-plugin-mock-server to handle only the routes that match the patterns provided in `urlPrefixes`. All other routes has to stay unaffected by vite-plugin-mock-server. But the middleware is applied for all routes, not only the ones listed in `urlPrefixes`. Applying middlewares for all routes may have unexpected consequences.

Although it is possible to circumvent this issue on the consumer's side (wrapping middlewares in conditional logic), the current behaviour seems counterintuitive and leads to hard-to-debug bugs in the consumer's application.

Would be great vite-plugin-mock-server affected only the routes listed in urlPrefixes (if provided).

I have created a vue project to reproduce the issue https://github.com/arfedulov/reproduce-vite-mock-server .
- clone the repo
- `npm i`
- `npm run dev`
- see the output in dev server's terminal

**Comment by arfedulov** [comment]
If this is something worth implementing, I would love to help and make a pull request.

**Comment by octoape** [comment]
Hello @arfedulov, welcome to submit a PR to fix this issue.
