### ISSUE TITLE
mock server hijacks console

### ISSUE THREAD

**Issue by vinodhum** [enjoycoding/vite-plugin-mock-server#9]
Hi,
Mock server output is hijacking app output, any errors from app build is not showing up on terminal. is there a way to disable it ?

```
[vite-plugin-mock-server] mock server started. options = {
  logLevel: 'off',
  urlPrefixes: [ '/digital' ],
  mockRootDir: './mock',
  mockJsSuffix: '.mock.js',
  mockTsSuffix: '.mock.ts',
  noHandlerResponse404: true,
```

**Comment by mumashanren** [comment]
Please describe the problem in detail. I didn't find this problem in my test.

**Comment by vinodhum** [comment]
when you run the dev using `npm start` it hides the react app related terminal outputs instead just shows plugin output

**Comment by mumashanren** [comment]
Generally, you need to view the react application log on the browser developer tool console.
